/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select country, count(distinct customer_key) as total_customers
from dim_customers
group by country
order by total_customers;


select 
case
	when country = 'n/a' then "India" 
    else country
end as country,
count(distinct customer_key) as total_customers
from dim_customers
group by country
order by total_customers;


-- Find total customers by gender
select gender, count(customer_key) from dim_customers group by gender;

select
case
	When gender = 'n/a' then 'Trans'
    else gender
end as gender,
count(customer_key)
from dim_customers
group by gender;


-- Find total products by category
select category, count(product_key) as total_products from dim_products group by category;


-- What is the average costs in each category?
select category, round(avg(cost),2) as avg_cost from dim_products group by category;


-- What is the total revenue generated for each category?
select p.category as category , sum(f.sales_amount) as revenue
from dim_products as p
inner join fact_sales as f on
p.product_key = f.product_key
group by category
order by revenue desc;


-- What is the total revenue generated by each customer?
select c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as revenue
from dim_customers as c
inner join fact_sales as f
on c.customer_key = f.customer_key
group by 
customer_key,
first_name,
last_name
order by revenue desc;


-- What is the distribution of sold items across countries?
select 
case 
	when country = 'n/a' then 'India'
	else country
end as country,
sum(f.quantity) as total_item_sold
from dim_customers as c
inner join fact_sales as f on
c.customer_key = f.customer_key
group by country
order by total_item_sold desc;